# Generated by Django 3.0.4 on 2020-05-29 20:30

from django.db import migrations, models
import django.utils.timezone
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('mobile', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('id_card', models.ImageField(default='default.png', upload_to='id_card')),
                ('reg_type', models.CharField(max_length=9)),
                ('num_of_tickets', models.IntegerField()),
                ('reg_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
