# Generated by Django 3.0.4 on 2020-05-30 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='reg_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
